
package com.mycompany.roteiro_04_01.gui;

import com.mycompany.roteiro_04_01.classes.Medico;
import com.mycompany.roteiro_04_01.gerenciadores.GerenciadorMedico;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author matheus henrique
 */
public class DlgMedico extends javax.swing.JDialog {

   private GerenciadorMedico gerente;
   private boolean editando;
   private String crmEscolhido;
   
    public DlgMedico(java.awt.Frame parent, boolean modal) throws FileNotFoundException {
        super(parent, modal);
        initComponents();
        this.editando=false;
        this.gerente= new GerenciadorMedico();
        this.crmEscolhido="";
        this.habilitarCampos(false);
        this.atualizarListagem();
        
    }
  private void atualizarListagem(){
       String listagem=this.gerente.listar();
       edtListagem.setText(listagem);
      
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadMedico = new javax.swing.JLabel();
        panOpcoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        panPreencher = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        lblCrm = new javax.swing.JLabel();
        edtCrm = new javax.swing.JTextField();
        lblEspecialidade = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        edtHorario = new javax.swing.JTextField();
        edtEspecialidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtListagem = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCadMedico.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCadMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadMedico.setText("Cadastro De Medicos");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        panOpcoes.add(btnNovo);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panOpcoes.add(btnCancelar);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        panOpcoes.add(btnExcluir);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panOpcoes.add(btnEditar);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        panOpcoes.add(btnSalvar);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        panOpcoes.add(btnVoltar);

        lblNome.setText("Nome:");

        lblCrm.setText("CRM:");

        lblEspecialidade.setText("Especialidade:");

        lblHorario.setText("Horario:");

        javax.swing.GroupLayout panPreencherLayout = new javax.swing.GroupLayout(panPreencher);
        panPreencher.setLayout(panPreencherLayout);
        panPreencherLayout.setHorizontalGroup(
            panPreencherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPreencherLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panPreencherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panPreencherLayout.createSequentialGroup()
                        .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtNome))
                    .addGroup(panPreencherLayout.createSequentialGroup()
                        .addComponent(lblCrm, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtCrm, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(panPreencherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panPreencherLayout.createSequentialGroup()
                        .addComponent(lblEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panPreencherLayout.createSequentialGroup()
                        .addComponent(lblHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtHorario)))
                .addGap(27, 27, 27))
        );
        panPreencherLayout.setVerticalGroup(
            panPreencherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPreencherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panPreencherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panPreencherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCrm)
                    .addGroup(panPreencherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edtCrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblHorario)
                        .addComponent(edtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        edtListagem.setColumns(20);
        edtListagem.setRows(5);
        jScrollPane1.setViewportView(edtListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCadMedico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panOpcoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panPreencher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCadMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panOpcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panPreencher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
      dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.habilitarCampos(true);
        this.limparCampos();
        this.editando=false;
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.habilitarCampos(false);
        this.limparCampos();
        this.editando=false;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        this.crmEscolhido=JOptionPane.showInputDialog("Digite CRM do medico para excluir");
        Medico medico=this.gerente.pesquisar(crmEscolhido);
        
        if(medico!= null){
           this.gerente.remover(crmEscolhido);
           JOptionPane.showMessageDialog(this, "Medico removido");
          try {
            this.gerente.salvarNoArquivo();
      } catch (IOException e) {
    JOptionPane.showMessageDialog(this, "Erro ao salvar arquivo: " + e.getMessage());
} 
           this.habilitarCampos(false);
           this.limparCampos();
           this.editando= false;
           
           String listagem=gerente.listar();
           edtListagem.setText(listagem);
            
        }else{
            JOptionPane.showMessageDialog(this, "Medico nao encontrado");
        }
   
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.crmEscolhido= JOptionPane.showInputDialog("Digite crm do medico que deseja editar");
        Medico medicoEscolhido=this.gerente.pesquisar(crmEscolhido);
        
       if(medicoEscolhido!= null){
            
           this.editando=true;
           this.limparCampos();
           this.habilitarCampos(true);
           
           this.objetoParaCampos(medicoEscolhido);
     }else{
        JOptionPane.showMessageDialog(this, "Medico nao encontrado");
       }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Medico novoMedico = this.camposParaObjeto();
        
        if(editando== true){
            this.gerente.atualizar(crmEscolhido, novoMedico);
     }else{
         this.gerente.add(novoMedico);
            
        }
       try {
        this.gerente.salvarNoArquivo(); 
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Erro ao salvar arquivo: " + e.getMessage());
    }
        this.limparCampos();
        this.habilitarCampos(false);
        this.editando=false;
        
        this.atualizarListagem();
        
    }//GEN-LAST:event_btnSalvarActionPerformed
   public void habilitarCampos(boolean flag){
       edtNome.setEnabled(flag);
       edtCrm.setEnabled(flag);
       edtEspecialidade.setEnabled(flag);
       edtHorario.setEnabled(flag);
   }
   
   public void limparCampos(){
       edtNome.setText("");
       edtCrm.setText("");
       edtEspecialidade.setText("");
       edtHorario.setText("");
       
   }
   
   
   public void objetoParaCampos(Medico medico){
       edtNome.setText(medico.getNome());
       edtCrm.setText(medico.getCrm());
       edtEspecialidade.setText(medico.getEspecialidade());
       edtHorario.setText(medico.getHorariosDisponiveis());
       
       
   }
   public Medico camposParaObjeto(){
       
       Medico medico=new Medico();
       
       medico.setNome(edtNome.getText());
       medico.setCrm(edtCrm.getText());
       medico.setEspecialidade(edtEspecialidade.getText());
       medico.setHorariosDisponiveis(edtHorario.getText());
       
       return medico;
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField edtCrm;
    private javax.swing.JTextField edtEspecialidade;
    private javax.swing.JTextField edtHorario;
    private javax.swing.JTextArea edtListagem;
    private javax.swing.JTextField edtNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCadMedico;
    private javax.swing.JLabel lblCrm;
    private javax.swing.JLabel lblEspecialidade;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel panOpcoes;
    private javax.swing.JPanel panPreencher;
    // End of variables declaration//GEN-END:variables
}
